[package]
name = "mintaka-macros"
version = "0.0.5"
description = "Mintaka Macros"
repository = "https://github.com/Tribufu/Mintaka"
authors = ["Tribufu <contact@tribufu.com>"]
edition = "2021"
publish = false

[lib]
name = "mintaka_macros"
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
